"""
email_sender.py — Auto Email to Cybercrime Cell
Sends FIR PDF as email attachment using Gmail SMTP.

Setup (one-time):
1. Enable 2-Factor Authentication on your Gmail account
2. Go to: Google Account → Security → App Passwords
3. Generate a new App Password for "Mail"
4. Use that 16-character password here (NOT your real Gmail password)
"""

import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


CYBERCRIME_EMAIL = "cybercrime@gov.in"  # Official National Cybercrime Portal email


def send_fir_email(
    sender_email: str,
    sender_app_password: str,
    recipient_email: str,
    subject: str,
    body: str,
    pdf_bytes: bytes,
    pdf_filename: str,
) -> None:
    """
    Send an FIR PDF as an email attachment via Gmail SMTP.

    Parameters
    ----------
    sender_email : str
        Your Gmail address.
    sender_app_password : str
        16-character Gmail App Password (NOT your real password).
    recipient_email : str
        Recipient email (e.g., cybercrime@gov.in or local police email).
    subject : str
        Email subject line.
    body : str
        Email body text.
    pdf_bytes : bytes
        FIR PDF content as bytes.
    pdf_filename : str
        Filename for the attached PDF.
    """
    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = recipient_email
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    # Attach PDF
    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(pdf_bytes)
    encoders.encode_base64(attachment)
    attachment.add_header(
        "Content-Disposition",
        f'attachment; filename="{pdf_filename}"',
    )
    msg.attach(attachment)

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(sender_email, sender_app_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())


def build_fir_email_body(username: str, comment: str, toxicity_score: float, case_id: str, post_url: str = "N/A") -> str:
    """Build a professional email body for the cybercrime complaint."""
    now = datetime.now().strftime("%d %B %Y, %I:%M %p")
    return f"""To,
The Nodal Officer,
National Cyber Crime Reporting Portal

Subject: Cyber Harassment Complaint — Case {case_id}

Respected Sir/Madam,

I am writing to formally report an incident of cyber harassment detected and documented by Safeguard AI, an automated cyber harassment detection system.

INCIDENT DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Case ID         : {case_id}
Date & Time     : {now}
Platform        : Instagram / Social Media
Post URL        : {post_url}
Accused Handle  : @{username}
Toxicity Score  : {toxicity_score:.2%}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

OFFENSIVE COMMENT:
"{comment}"

The above content has been classified as highly toxic and violates the following provisions:
• Information Technology Act, 2000 — Section 66A (Offensive Electronic Communication)
• Information Technology Act, 2000 — Section 67 (Obscene Material)
• Indian Penal Code — Section 509 (Insult to Modesty)

Please find the attached First Information Report (FIR) generated by Safeguard AI for your reference.

I request you to take appropriate legal action against the accused.

Thanking you,
[Complainant Name]
[Contact Number]
[Address]

---
This complaint was auto-generated by Safeguard AI v2.0
Report generated on: {now}
"""
