"""
fir_generator.py — FIR (First Information Report) PDF Generator
Generates a professional FIR document for each vulgar comment.
Compatible with fpdf 1.7.2.
"""
from __future__ import annotations

import io
import uuid
from datetime import datetime
from fpdf import FPDF

SEVERITY_COLORS = {
    "Vulgar": (180, 30, 30),
    "High":   (200, 90, 20),
    "Medium": (180, 150, 0),
    "Low":    (30, 140, 70),
}


def _pdf_to_bytes(pdf: FPDF) -> bytes:
    """Correctly extract bytes from fpdf 1.7.2 (output('S') returns a string)."""
    raw = pdf.output(dest="S")          # fpdf 1.7.2: returns latin-1 str
    if isinstance(raw, (bytes, bytearray)):
        return bytes(raw)
    return raw.encode("latin-1")        # encode back to raw bytes


def _safe(text: str) -> str:
    """Strip emojis and non-latin-1 characters so fpdf 1.7.2 doesn't crash."""
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class FIRReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(180, 30, 30)
        self.cell(0, 10, "FIRST INFORMATION REPORT (FIR)", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Safeguard AI - Automated Cyber Harassment Detection System", ln=True, align="C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(5)

    def footer(self):
        self.set_y(-18)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}  |  Safeguard AI v2.0  |  Confidential", align="C", ln=True)


def generate_fir_pdf(
    comment: str,
    username: str,
    toxicity_score: float,
    severity: str,
    sub_scores: dict | None = None,
    post_url: str = "N/A",
) -> bytes:
    """Generate a FIR PDF for a single harassing comment. Returns bytes."""
    pdf = FIRReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=25)

    now = datetime.now()
    case_id = f"SG-{now.strftime('%Y%m%d')}-{str(uuid.uuid4())[:8].upper()}"
    color = SEVERITY_COLORS.get(severity, (40, 40, 40))
    comment  = _safe(comment)
    username = _safe(username)
    post_url = _safe(post_url)

    def section(title):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(40, 40, 40)
        pdf.set_fill_color(245, 245, 250)
        pdf.cell(0, 8, f"  {title}", ln=True, fill=True)
        pdf.set_text_color(60, 60, 60)
        pdf.set_font("Helvetica", "", 10)
        pdf.ln(1)

    def field(label, value, value_color=None):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(80, 80, 100)
        pdf.cell(52, 7, f"{label}:", ln=False)
        pdf.set_font("Helvetica", "", 10)
        if value_color:
            pdf.set_text_color(*value_color)
        else:
            pdf.set_text_color(40, 40, 40)
        pdf.cell(0, 7, str(value), ln=True)
        pdf.set_text_color(60, 60, 60)

    # --- Section 1: Case Details ---
    section("1.  CASE DETAILS")
    field("Case ID", case_id)
    field("Date & Time", now.strftime("%d %B %Y, %I:%M:%S %p"))
    field("Platform", "Instagram")
    field("Post URL", post_url[:80] + "..." if len(post_url) > 80 else post_url)
    field("Generated By", "Safeguard AI v2.0 (Automated)")
    pdf.ln(3)

    # --- Section 2: Accused ---
    section("2.  ACCUSED DETAILS")
    field("Instagram Handle", f"@{username}")
    field("Account Type", "Public / Unknown")
    pdf.ln(3)

    # --- Section 3: Offensive Content ---
    section("3.  OFFENSIVE CONTENT")
    pdf.set_font("Helvetica", "BI", 10)
    pdf.set_text_color(80, 30, 30)
    pdf.multi_cell(0, 7, f'"{comment}"')
    pdf.ln(2)
    field("Toxicity Score", f"{toxicity_score:.4f}  ({toxicity_score*100:.1f}%)")
    field("Severity Classification", severity.upper(), value_color=color)
    pdf.ln(2)

    # Sub-scores if available
    if sub_scores:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(80, 80, 100)
        pdf.cell(0, 7, "Toxicity Sub-Labels:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        for label, score in sub_scores.items():
            bar_len = int(score * 50)
            bar = "#" * bar_len + "-" * (50 - bar_len)
            pdf.cell(0, 6, f"  {label:<20} {score:.3f}  [{bar}]", ln=True)
    pdf.ln(3)

    # --- Section 4: Legal References ---
    section("4.  APPLICABLE LEGAL PROVISIONS")
    laws = [
        "IT Act 2000 - Sec 66A: Sending offensive/menacing messages electronically",
        "IT Act 2000 - Sec 67: Publishing obscene material in electronic form",
        "IT Act 2000 - Sec 66E: Violation of privacy",
        "IPC Sec 509: Acts intended to insult the modesty of a person",
        "IPC Sec 507: Criminal intimidation by anonymous communication",
    ]
    for law in laws:
        pdf.set_text_color(60, 60, 80)
        pdf.cell(5, 6, "-", ln=False)
        pdf.multi_cell(0, 6, f" {law}")
    pdf.ln(3)

    # --- Statutory Warning ---
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(180, 30, 30)
    pdf.cell(0, 8, "STATUTORY WARNING", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 30, 30)
    pdf.multi_cell(
        0, 6,
        "Cyber harassment is a punishable offence under the Information Technology Act, 2000 "
        "and the Indian Penal Code. Offenders may face up to three years imprisonment and/or a fine. "
        "This report is auto-generated by Safeguard AI and may be submitted as evidence to law enforcement."
    )
    pdf.ln(5)

    # --- Signature ---
    pdf.set_text_color(40, 40, 40)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(90, 7, "Complainant Signature: ____________________", ln=False)
    pdf.cell(0, 7, "Date: ____________________", ln=True)

    return _pdf_to_bytes(pdf)


def generate_batch_fir_pdf(vulgar_rows: list[dict], post_url: str = "N/A") -> bytes:
    """Generate a single consolidated FIR PDF for all vulgar comments."""
    pdf = FIRReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=25)

    now = datetime.now()
    batch_id = f"BATCH-SG-{now.strftime('%Y%m%d%H%M')}"

    for i, row in enumerate(vulgar_rows, 1):
        pdf.add_page()

        color = SEVERITY_COLORS.get(row.get("Severity", "Vulgar"), (40, 40, 40))
        username = _safe(row["Username"])
        comment  = _safe(row["Comment"])
        url      = _safe(post_url)
        sub = {
            "Toxic":        row.get("Toxic", 0),
            "Obscene":      row.get("Obscene", 0),
            "Threat":       row.get("Threat", 0),
            "Insult":       row.get("Insult", 0),
            "Identity Atk": row.get("Identity Attack", 0),
        }

        # Batch header
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(0, 8, f"COMPLAINT #{i} of {len(vulgar_rows)}  |  {batch_id}", ln=True)
        pdf.set_draw_color(200, 50, 50)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        # Case details
        case_id = f"SG-{now.strftime('%Y%m%d')}-{str(uuid.uuid4())[:8].upper()}"
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)

        def bfield(label, value, vc=None):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(80, 80, 100)
            pdf.cell(52, 7, f"{label}:", ln=False)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*(vc or (40, 40, 40)))
            pdf.cell(0, 7, str(value), ln=True)
            pdf.set_text_color(60, 60, 60)

        bfield("Case ID", case_id)
        bfield("Date & Time", now.strftime("%d %B %Y, %I:%M:%S %p"))
        bfield("Post URL", url[:70] + "..." if len(url) > 70 else url)
        bfield("Instagram Handle", f"@{username}")
        bfield("Severity", row["Severity"].upper(), vc=color)
        bfield("Toxicity Score", f"{row['Toxicity Score']:.4f}  ({row['Toxicity Score']*100:.1f}%)")
        pdf.ln(2)

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(80, 30, 30)
        pdf.cell(0, 7, "Offensive Comment:", ln=True)
        pdf.set_font("Helvetica", "BI", 10)
        pdf.multi_cell(0, 7, f'"{comment}"')
        pdf.ln(2)

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(80, 80, 100)
        pdf.cell(0, 6, "Toxicity Sub-Labels:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        for lbl, val in sub.items():
            bar_len = int(val * 50)
            bar = "#" * bar_len + "-" * (50 - bar_len)
            pdf.cell(0, 6, f"  {lbl:<20} {val:.3f}  [{bar}]", ln=True)
        pdf.ln(3)

        # Legal references
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.set_fill_color(245, 245, 250)
        pdf.cell(0, 8, "  APPLICABLE LEGAL PROVISIONS", ln=True, fill=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 80)
        for law in [
            "IT Act 2000 - Sec 66A: Sending offensive/menacing messages electronically",
            "IT Act 2000 - Sec 67: Publishing obscene material in electronic form",
            "IPC Sec 509: Acts intended to insult the modesty of a person",
        ]:
            pdf.cell(5, 6, "-", ln=False)
            pdf.multi_cell(0, 6, f" {law}")
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(90, 7, "Complainant Signature: ____________________", ln=False)
        pdf.cell(0, 7, "Date: ____________________", ln=True)

    return _pdf_to_bytes(pdf)
